document:
  name: Accesso aperto ai contributi della ricerca dell'INGV
  description: |
    Accesso aperto ai contributi della ricerca dell'Istituto Nazionale di Geofisica e Vulcanologia.
  tags:
    - INGV
    - politica dei dati
    - database
    - dataset
    - ricerca scientifica
    - metadati
    - FAIR
    - accesso aperto
